export default class AjccMacis {
  constructor(){ this.name='AJCC 8th + MACIS'; }
  render(container){
    container.innerHTML=`<div class="form-grid"><div><label>Age</label><input id="age" type="number" step="0.1"></div><div><label>Tumor size (cm)</label><input id="tumor" type="number" step="0.1"></div><div><label>Metastasis</label><select id="met"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Extrathyroidal extension</label><select id="ext"><option value="0">None</option><option value="1">Only strap muscle</option><option value="2">SubQ/larynx/trachea/esophagus/RLN</option><option value="3">Prevertebral fascia/major vessels</option></select></div><div><label>Lymph node</label><select id="ln"><option value="0">None</option><option value="1">Central</option><option value="2">Lateral</option><option value="3">Unknown</option></select></div><div><label>Incomplete resection</label><select id="res"><option value="0">No</option><option value="1">Yes</option></select></div><div><label>Local invasion</label><select id="inv"><option value="0">No</option><option value="1">Yes</option></select></div></div><button id="calc" class="calc-button">Calculate</button><div class="result" id="result"></div>`;
    container.querySelector('#calc').addEventListener('click',()=>{const age=parseFloat(container.querySelector('#age').value);const tumor=parseFloat(container.querySelector('#tumor').value);const met=+container.querySelector('#met').value;const ext=+container.querySelector('#ext').value;const ln=+container.querySelector('#ln').value;const res=+container.querySelector('#res').value;const inv=+container.querySelector('#inv').value;if(!(age>0&&tumor>=0))return;let stage='';if(age<55){stage=met===0?'I':'II';}else if(met===1){stage='IV B';}else if(ext===0){if(tumor<=4){stage=(ln===1||ln===2)?'II':'I';}else{stage='II';}}else if(ext===1){stage='II';}else if(ext===2){stage='III';}else{stage='IV A';}
      let score=age<40?3.1:0.08*age;score+=0.3*tumor;if(res===1)score+=1;if(inv===1)score+=1;if(met===1)score+=3;
      container.querySelector('#result').textContent=`Stage: ${stage} | MACIS: ${score.toFixed(2)}`;});
  }
}
